/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hien_schoolnotescan_CppCore */

#ifndef _Included_com_hien_schoolnotescan_CppCore
#define _Included_com_hien_schoolnotescan_CppCore
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hien_schoolnotescan_CppCore
 * Method:    nativeInit
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_hien_schoolnotescan_CppCore_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     com_hien_schoolnotescan_CppCore
 * Method:    nativeRelease
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_hien_schoolnotescan_CppCore_nativeRelease
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_hien_schoolnotescan_CppCore
 * Method:    nativeDetectRect
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_com_hien_schoolnotescan_CppCore_nativeDetectRect
  (JNIEnv *, jclass, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
